### ISSUE TITLE
Warning in current version of HA

### ISSUE THREAD

**Issue by Bullischorsch** [nielstron/ha_blnet#10]
Moin,

after updating to 2024.3 of HA I got this warning in the logs:

TEMP_CELSIUS was used from blnet, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfTemperature.CELSIUS instead, please report it to the author of the 'blnet' custom integration

It would be great if this can get solved, since I like the addon I would like to go on using it. 

Regards and thanks 
Georg

**Comment by orpdk** [comment]
mine stopped working ???
![image](https://github.com/nielstron/ha_blnet/assets/108662009/3f14bf61-acff-42bb-8a26-f81e52244e7e)

**Comment by Bullischorsch** [comment]
created change and pull request: https://github.com/nielstron/ha_blnet/pull/14
